/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/vkpwlBhurUH
 */
import Link from "next/link"
import Image from "next/image";

export default function hero() {
  return (
    <section className="grid items-center w-full min-h-[80vh] py-12 gap-12">
      <div className="container px-4 md:px-6">
        <div className="flex flex-col items-center justify-center space-y-4 text-center">
          <div className="space-y-2">
            <h1 className="text-3xl font-bold tracking-tighter sm:text-5xl">Cosmic Fortunes</h1>
            <p className="max-w-[700px] text-gray-500 md:text-xl dark:text-gray-400">
              Discover your destiny. Let the wisdom of the cards guide you.
            </p>
          </div>
          <div>
            <Link
              className="inline-flex h-10 items-center justify-center rounded-md border border-gray-200 bg-white px-8 text-sm font-medium shadow-sm transition-colors hover:bg-gray-100 hover:text-gray-900 focus-visible:outline-none focus-visible:ring-1 focus-visible:ring-gray-950 disabled:pointer-events-none disabled:opacity-50 dark:border-gray-800 dark:bg-gray-950 dark:hover:bg-gray-800 dark:hover:text-gray-50 dark:focus-visible:ring-gray-300 dark:border-gray-800"
              href="/reading"
            >
              Start Your Journey
            </Link>
          </div>
        </div>
      </div>
     

      <div className="w-full aspect-video overflow-hidden rounded-t-lg sm:rounded-t-none">
        <Image
          alt="Hero"
          className="object-top"
          height={1080}
          src="/galaxy-hero.png"
          layout="responsive"
          objectFit="cover"
          width={1920}
        />
      </div>
    </section>
  )
}
